/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/AWTForms/Frame.java to edit this template
 */
package ejemplocanvas;

import java.awt.Color;

/**
 *
 * @author rafaa
 */
public class EjemploCanvasAPP extends java.awt.Frame {
   

    /**
     * Creates new form EjemploCanvasAPP
     */
    private static MiCanvas cv = new MiCanvas(600,400);
    
    public EjemploCanvasAPP() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        botonsalir = new java.awt.Button();

        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosing(java.awt.event.WindowEvent evt) {
                exitForm(evt);
            }
        });
        setLayout(null);

        botonsalir.setLabel("salir");
        botonsalir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonsalirActionPerformed(evt);
            }
        });
        add(botonsalir);
        botonsalir.setBounds(270, 350, 38, 24);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * Exit the Application
     */
    private void exitForm(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_exitForm
        System.out.println("No me da la gana");
        cv.ponCadena("no quiero");
    }//GEN-LAST:event_exitForm

    private void botonsalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonsalirActionPerformed
        // TODO add your handling code here:
        System.exit(0);
    }//GEN-LAST:event_botonsalirActionPerformed


    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) throws InterruptedException {
        EjemploCanvasAPP f = new EjemploCanvasAPP(); //este es el objeto frame
        f.setSize(600, 400);
        f.setBackground(Color.yellow);
        f.setTitle("Practica 3");
        f.setLocation(100, 50); //(0,0) ->arriba a la izquierda primer pixel
        
    
        f.add(cv);
        
        f.setVisible(true);
        Recurso r = new Recurso(cv);

        for (int i = 0; i < 10; i++) {
            r.incrementa(1);
        }
        Sumador h1 = new Sumador(0, r);
        Sumador h2 = new Sumador(1, r);
        Sumador h3 = new Sumador(1, r);

        h1.start();
        h2.start();
        h3.start();

        h1.join();
        h2.join();
        h3.join();

        int resultado[] = r.getContadores();
        System.out.println("El contador 1 vale " + resultado[0]);
        System.out.println("El contador 2 vale " + resultado[1]);

    }




    // Variables declaration - do not modify//GEN-BEGIN:variables
    private java.awt.Button botonsalir;
    // End of variables declaration//GEN-END:variables

}