/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/AWTForms/Frame.java to edit this template
 */
package practica8pcd;

import static java.lang.Thread.sleep;
import java.util.Random;
import java.util.logging.Level;
import java.util.logging.Logger;

/**
 *
 * @author usuario
 */
public class GeneradorAPP extends java.awt.Frame {

    private static SuperCanvas cv = new SuperCanvas(800, 600);

    /**
     * Creates new form GeneradorAPP
     */
    public GeneradorAPP() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosing(java.awt.event.WindowEvent evt) {
                exitForm(evt);
            }
        });

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * Exit the Application
     */
    private void exitForm(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_exitForm
        System.exit(0);
    }//GEN-LAST:event_exitForm

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        var generador = new GeneradorAPP();
        generador.setSize(800,600);
        generador.setTitle("Practica 8");
        generador.setLocation(100, 50);
        
        generador.add(cv);
        generador.setVisible(true);
        
        var rdm = new Random();

        var clientes = new Thread[20];
        var supermercado = new Supermercado();
        for (int i = 0; i < 20; i++) {
            if (rdm.nextInt(100) < 50) {
                clientes[i] = new Thread(new Tarjeta(supermercado, "Tarjeta-" + i, cv));
            } else {
                clientes[i] = new Thread(new Efectivo(supermercado, "Efectivo-" + i , cv));
            }
            clientes[i].start();
            try {
                sleep(1000);
            } catch (InterruptedException ex) {
                Logger.getLogger(GeneradorAPP.class.getName()).log(Level.SEVERE, null, ex);
            }
        }

        for (int i = 0; i < 20; i++) {
            try {
                clientes[i].join();
            } catch (InterruptedException ex) {
                Logger.getLogger(GeneradorAPP.class.getName()).log(Level.SEVERE, null, ex);
            }
        }
        try {
            sleep(3000);
        } catch (InterruptedException ex) {
            Logger.getLogger(GeneradorAPP.class.getName()).log(Level.SEVERE, null, ex);
        }
        System.exit(0);
    }


    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables
}
