/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JDialog.java to edit this template
 */
package Vista;

import com.toedter.calendar.JDateChooser;

/**
 *
 * @author rafaelMesaNombela
 */
public class JDialogCuotaSocios extends javax.swing.JDialog {

    /**
     * Creates new form JDialog1
     */
    public JDialogCuotaSocios() {
        initComponents();
// Configura cualquier propiedad adicional si es necesario
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        codigoSocio = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jButtonVerCuotaSocio = new javax.swing.JButton();
        jButtonCerrarCuotaSocio = new javax.swing.JButton();
        jLabelLabelNumActividadesSocio = new javax.swing.JLabel();
        jLabelNumActividadesSocio = new javax.swing.JLabel();
        jLabelLabelCuotaMensualSocio = new javax.swing.JLabel();
        jLabelCuotaMensualSocio = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        codigoSocio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                codigoSocioActionPerformed(evt);
            }
        });

        jLabel1.setText("Código de  Socio");

        jButtonVerCuotaSocio.setText("Ver Cuota");
        jButtonVerCuotaSocio.setActionCommand("VerCuota");
        jButtonVerCuotaSocio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonVerCuotaSocioActionPerformed(evt);
            }
        });

        jButtonCerrarCuotaSocio.setText("Cerrar");
        jButtonCerrarCuotaSocio.setActionCommand("CerrarCuotaSocios");

        jLabelNumActividadesSocio.setText("jLabel3");

        jLabelCuotaMensualSocio.setText("jLabel5");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(67, 67, 67)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(jButtonCerrarCuotaSocio)
                        .addGap(33, 33, 33))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jButtonVerCuotaSocio)
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(jLabel1)
                                    .addGap(18, 18, 18)
                                    .addComponent(codigoSocio, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabelLabelNumActividadesSocio, javax.swing.GroupLayout.DEFAULT_SIZE, 128, Short.MAX_VALUE)
                                .addGap(33, 33, 33)))
                        .addComponent(jLabelNumActividadesSocio, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(118, 118, 118))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabelLabelCuotaMensualSocio, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabelCuotaMensualSocio, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(118, 118, 118))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(41, 41, 41)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(codigoSocio, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1))
                .addGap(18, 18, 18)
                .addComponent(jButtonVerCuotaSocio)
                .addGap(64, 64, 64)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelLabelNumActividadesSocio)
                    .addComponent(jLabelNumActividadesSocio))
                .addGap(31, 31, 31)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelLabelCuotaMensualSocio)
                    .addComponent(jLabelCuotaMensualSocio))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 48, Short.MAX_VALUE)
                .addComponent(jButtonCerrarCuotaSocio)
                .addGap(14, 14, 14))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void codigoSocioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_codigoSocioActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_codigoSocioActionPerformed

    private void jButtonVerCuotaSocioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonVerCuotaSocioActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButtonVerCuotaSocioActionPerformed

    
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JTextField codigoSocio;
    public javax.swing.JButton jButtonCerrarCuotaSocio;
    public javax.swing.JButton jButtonVerCuotaSocio;
    private javax.swing.JLabel jLabel1;
    public javax.swing.JLabel jLabelCuotaMensualSocio;
    public javax.swing.JLabel jLabelLabelCuotaMensualSocio;
    public javax.swing.JLabel jLabelLabelNumActividadesSocio;
    public javax.swing.JLabel jLabelNumActividadesSocio;
    // End of variables declaration//GEN-END:variables
}
