/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Vista;

/**
 *
 * @author rafaa
 */
public class vistaPrincipal extends javax.swing.JFrame {

    /**
     * Creates new form vistaPrincipal
     */
    public vistaPrincipal() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jMenuItem1 = new javax.swing.JMenuItem();
        jMenuBar2 = new javax.swing.JMenuBar();
        jMenu4 = new javax.swing.JMenu();
        jMenu5 = new javax.swing.JMenu();
        jMenuItem2 = new javax.swing.JMenuItem();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        GestionMonitores = new javax.swing.JMenuItem();
        jMenu2 = new javax.swing.JMenu();
        GestionSocios = new javax.swing.JMenuItem();
        jMenu3 = new javax.swing.JMenu();
        GestionActividades = new javax.swing.JMenuItem();
        jMenu8 = new javax.swing.JMenu();
        jMenuItemActualizacionCategorias = new javax.swing.JMenuItem();
        jMenuItemCuotaActividad = new javax.swing.JMenuItem();
        CuotaSocios = new javax.swing.JMenuItem();
        jMenu7 = new javax.swing.JMenu();
        VolverPrincipal = new javax.swing.JMenuItem();
        jMenu6 = new javax.swing.JMenu();
        SalirAplicacion = new javax.swing.JMenuItem();

        jMenuItem1.setText("jMenuItem1");

        jMenu4.setText("File");
        jMenuBar2.add(jMenu4);

        jMenu5.setText("Edit");
        jMenuBar2.add(jMenu5);

        jMenuItem2.setText("jMenuItem2");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Gestión de Gimnasio \"Body Perfect\"");

        jMenu1.setText("Monitores");

        GestionMonitores.setText("Gestión Monitores");
        GestionMonitores.setActionCommand("GestionMonitores");
        GestionMonitores.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                GestionMonitoresActionPerformed(evt);
            }
        });
        jMenu1.add(GestionMonitores);

        jMenuBar1.add(jMenu1);

        jMenu2.setText("Socios");

        GestionSocios.setText("Gestión de socios");
        GestionSocios.setActionCommand("GestionSocios");
        jMenu2.add(GestionSocios);

        jMenuBar1.add(jMenu2);

        jMenu3.setText("Actividades");

        GestionActividades.setText("Gestión de actividades");
        GestionActividades.setActionCommand("GestionActividades");
        jMenu3.add(GestionActividades);

        jMenuBar1.add(jMenu3);

        jMenu8.setText("Ampliación");

        jMenuItemActualizacionCategorias.setText("Actualización de Categorias");
        jMenuItemActualizacionCategorias.setActionCommand("ActualizacionCategorias");
        jMenu8.add(jMenuItemActualizacionCategorias);

        jMenuItemCuotaActividad.setText("Cuota Actividad");
        jMenuItemCuotaActividad.setActionCommand("CuotaActividad");
        jMenu8.add(jMenuItemCuotaActividad);

        CuotaSocios.setText("Cuota Socios");
        CuotaSocios.setActionCommand("CuotaSocios");
        jMenu8.add(CuotaSocios);

        jMenuBar1.add(jMenu8);

        jMenu7.setText("Volver");

        VolverPrincipal.setText("Volver a la pagina Principal");
        VolverPrincipal.setActionCommand("VolverPrincipal");
        jMenu7.add(VolverPrincipal);

        jMenuBar1.add(jMenu7);

        jMenu6.setText("Salir");

        SalirAplicacion.setText("Salir de la Aplicación");
        SalirAplicacion.setActionCommand("SalirAplicacion");
        jMenu6.add(SalirAplicacion);

        jMenuBar1.add(jMenu6);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 924, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 572, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void GestionMonitoresActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_GestionMonitoresActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_GestionMonitoresActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JMenuItem CuotaSocios;
    public javax.swing.JMenuItem GestionActividades;
    public javax.swing.JMenuItem GestionMonitores;
    public javax.swing.JMenuItem GestionSocios;
    public javax.swing.JMenuItem SalirAplicacion;
    public javax.swing.JMenuItem VolverPrincipal;
    public javax.swing.JMenu jMenu1;
    public javax.swing.JMenu jMenu2;
    private javax.swing.JMenu jMenu3;
    private javax.swing.JMenu jMenu4;
    private javax.swing.JMenu jMenu5;
    private javax.swing.JMenu jMenu6;
    private javax.swing.JMenu jMenu7;
    private javax.swing.JMenu jMenu8;
    public javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuBar jMenuBar2;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenuItem jMenuItem2;
    public javax.swing.JMenuItem jMenuItemActualizacionCategorias;
    public javax.swing.JMenuItem jMenuItemCuotaActividad;
    // End of variables declaration//GEN-END:variables
}
